import { useCallback, useEffect, useMemo, useState } from "react";
import { Bot, Check, FileSearch, ShieldCheck, UserCheck, Users, X } from "lucide-react";
import { atlasAgentApi, type Activity, type AssignmentResult, type AtlasRequirement, type Coverage, type Health, type Recommendation, type TaskProposal, type Workload } from "@/lib/api/atlasAgentApi";
import { Pill } from "@/components/common/Primitives";

export function AtlasAgentPanel({ projectId }: { projectId: string }) {
  const [requirements, setRequirements] = useState<AtlasRequirement[]>([]);
  const [proposals, setProposals] = useState<TaskProposal[]>([]);
  const [coverage, setCoverage] = useState<Coverage | null>(null);
  const [health, setHealth] = useState<Health | null>(null);
  const [team, setTeam] = useState<Workload[]>([]);
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [activity, setActivity] = useState<Activity[]>([]);
  const [tasks, setTasks] = useState<Array<{ id: number; title: string; assigned_to?: number; complexity: string; priority: string }>>([]);
  const [assignmentResult, setAssignmentResult] = useState<AssignmentResult | null>(null);
  const [selectedMembers, setSelectedMembers] = useState<Record<number, number>>({});
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => {
    try {
      const [nextRequirements, nextProposals, nextCoverage, nextHealth, nextTeam, nextRecommendations, nextActivity, nextTasks] = await Promise.all([
        atlasAgentApi.requirements(projectId), atlasAgentApi.proposals(projectId), atlasAgentApi.coverage(projectId), atlasAgentApi.health(projectId),
        atlasAgentApi.workload(projectId), atlasAgentApi.recommendations(projectId), atlasAgentApi.activity(projectId), atlasAgentApi.tasks(projectId),
      ]);
      setRequirements(nextRequirements); setProposals(nextProposals); setCoverage(nextCoverage); setHealth(nextHealth); setError(null);
      setTeam(nextTeam); setRecommendations(nextRecommendations); setActivity(nextActivity); setTasks(nextTasks);
    } catch (err) { setError(err instanceof Error ? err.message : "Unable to load Atlas Agent"); }
  }, [projectId]);
  useEffect(() => { void refresh(); }, [refresh]);
  const act = async (action: () => Promise<unknown>) => { setBusy(true); setError(null); try { await action(); await refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Action failed"); } finally { setBusy(false); } };
  const uncovered = useMemo(() => requirements.filter(r => r.taskIds.length === 0 && !r.proposalIds.some(id => proposals.find(p => p.id === id)?.state === "PROPOSED")), [requirements, proposals]);
  const pending = proposals.filter(p => p.state === "PROPOSED");
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-primary/20 bg-primary/5 p-5">
      <div><div className="flex items-center gap-2 font-display text-lg font-semibold"><Bot className="h-5 w-5 text-primary" /> Atlas Agent</div><p className="mt-1 text-xs text-muted-foreground">Observe → retrieve → reason → propose → approve → act → update state</p></div>
      <button disabled={busy} onClick={() => act(() => atlasAgentApi.analyze(projectId))} className="rounded-md bg-primary px-3 py-2 text-xs font-medium text-primary-foreground disabled:opacity-50"><FileSearch className="mr-2 inline h-3.5 w-3.5" />Analyze PRD</button>
    </div>
    {error && <div className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-xs text-destructive">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <Metric label="PRD coverage" value={`${coverage?.coveragePercent ?? 0}%`} /><Metric label="Requirements" value={coverage?.requirementsTotal ?? 0} /><Metric label="Uncovered" value={coverage?.uncovered ?? 0} /><Metric label="Awaiting approval" value={health?.pendingApprovals ?? 0} />
    </div>
    {coverage && <div><div className="mb-2 flex justify-between text-xs"><span>Requirement coverage</span><span>{coverage.covered} covered · {coverage.partiallyCovered} partial · {coverage.uncovered} uncovered</span></div><div className="h-2 overflow-hidden rounded-full bg-border"><div className="h-full bg-primary" style={{ width: `${coverage.coveragePercent}%` }} /></div></div>}
    <Section title="Requirements" count={requirements.length}>{requirements.length ? requirements.map(r => <div key={r.id} className="rounded-lg border border-border p-4"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs text-primary">{r.id}</span><span className="text-sm font-medium">{r.title}</span><Pill tone="muted">{r.priority}</Pill></div><p className="mt-2 text-xs text-muted-foreground">{r.description}</p><p className="mt-2 text-[11px] text-muted-foreground">Source: document #{r.source.documentId}{r.source.section ? ` · ${r.source.section}` : ""} · {r.taskIds.length} linked task(s)</p></div>) : <Empty text="Analyze a processed PRD to extract requirements." />}</Section>
    <Section title="Proposed work" count={pending.length}>{pending.length ? pending.map(p => <div key={p.id} className="rounded-lg border border-border p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-medium">{p.title}</p><p className="mt-1 text-[11px] text-muted-foreground">From {p.requirementIds.join(", ")} · confidence {Math.round(p.confidence * 100)}%</p></div><div className="flex gap-2"><button disabled={busy} aria-label="Reject proposal" onClick={() => act(() => atlasAgentApi.reject(p.id))} className="rounded border border-border p-2 hover:bg-destructive/10"><X className="h-3.5 w-3.5" /></button><button disabled={busy} onClick={() => act(() => atlasAgentApi.approve(p.id))} className="rounded bg-primary px-3 py-2 text-xs text-primary-foreground"><Check className="mr-1 inline h-3.5 w-3.5" />Approve</button></div></div><ul className="mt-3 list-inside list-disc text-xs text-muted-foreground">{p.acceptanceCriteria.map(item => <li key={item}>{item}</li>)}</ul></div>) : <Empty text="No proposals are awaiting approval." />}</Section>
    <Section title="Missing coverage" count={uncovered.length}>{uncovered.length ? uncovered.map(r => <div key={r.id} className="flex items-center justify-between rounded-lg border border-warning/30 p-3"><span className="text-xs"><b>{r.id}</b> — {r.title}</span><button disabled={busy} onClick={() => act(() => atlasAgentApi.generate(projectId, [r.id]))} className="rounded border border-primary/30 px-2.5 py-1.5 text-xs text-primary">Generate proposal</button></div>) : <Empty text="Every requirement is covered or has proposed work." />}</Section>
    {health && <Section title="Deterministic project health"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Completion" value={`${health.completionPercent}%`} /><Metric label="Blocked tasks" value={health.blockedTasks} /><Metric label="Unassigned tasks" value={health.unassignedTasks} /></div><p className="mt-3 flex items-center gap-2 text-[11px] text-muted-foreground"><ShieldCheck className="h-3.5 w-3.5 text-primary" />Business-state metrics are calculated from stored records; the model cannot invent or mutate them.</p></Section>}
    <Section title="Team workload" count={team.length}>{team.length ? <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full text-left text-xs"><thead className="bg-surface text-muted-foreground"><tr><th className="p-3">Member</th><th className="p-3">Role</th><th className="p-3">Skills</th><th className="p-3">Active</th><th className="p-3">High</th><th className="p-3">Capacity</th></tr></thead><tbody>{team.map(member => <tr key={member.memberId} className="border-t border-border"><td className="p-3 font-medium">{member.name}</td><td className="p-3">{member.projectRole.replaceAll("_", " ")}</td><td className="p-3 text-muted-foreground">{member.skills.join(", ") || "—"}</td><td className="p-3">{member.activeTasks}</td><td className="p-3">{member.highPriorityTasks}</td><td className="p-3"><Pill tone="muted">{member.workloadIndicator}</Pill></td></tr>)}</tbody></table></div> : <Empty text="Add project members with skills to enable assignment recommendations." />}</Section>
    <Section title="Assignment recommendations" count={recommendations.filter(item => item.state === "PROPOSED").length}>
      {assignmentResult && <div className="rounded-lg border border-primary/20 bg-primary/5 p-4 text-xs"><p className="font-medium">Assigned to user #{assignmentResult.assignedUserId}</p><p className="mt-1">Email: {assignmentResult.notification.status === "SENT" ? "Sent ✓" : assignmentResult.notification.status === "FAILED" ? "Failed — assignment was still completed" : "Skipped / not configured"}</p><p className="mt-1 text-muted-foreground">Context shared: {assignmentResult.contextShared.requirements} requirement(s), {assignmentResult.contextShared.documents} document(s)</p>{assignmentResult.notification.status === "FAILED" && <button disabled={busy} onClick={() => act(async () => setAssignmentResult(await atlasAgentApi.retryAssignmentEmail(assignmentResult.taskId)))} className="mt-2 rounded border border-primary/30 px-2.5 py-1.5 text-primary">Retry notification</button>}</div>}
      {tasks.filter(task => !task.assigned_to).map(task => { const recommendation = recommendations.find(item => item.taskId === task.id && item.state === "PROPOSED"); const selected = selectedMembers[task.id] ?? recommendation?.recommendedMemberId; return <div key={task.id} className="rounded-lg border border-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-medium">{task.title}</p><p className="mt-1 text-[11px] text-muted-foreground">{task.complexity} · {task.priority}</p></div>{recommendation ? <div className="flex flex-wrap gap-2"><select value={selected} onChange={e=>setSelectedMembers(v=>({...v,[task.id]:Number(e.target.value)}))} className="rounded border border-border bg-surface px-2 py-2 text-xs">{team.map(member=><option key={member.memberId} value={member.memberId}>{member.name} — {member.projectRole.replaceAll("_"," ")}</option>)}</select><button disabled={busy} onClick={() => act(async () => setAssignmentResult(await atlasAgentApi.approveAssignment(recommendation.id, selected)))} className="rounded bg-primary px-3 py-2 text-xs text-primary-foreground"><UserCheck className="mr-1 inline h-3.5 w-3.5" />Approve assignment</button></div> : <button disabled={busy || team.length === 0} onClick={() => act(() => atlasAgentApi.recommend(task.id))} className="rounded border border-primary/30 px-3 py-2 text-xs text-primary"><Users className="mr-1 inline h-3.5 w-3.5" />Recommend</button>}</div>{recommendation && <div className="mt-3 rounded-md bg-surface p-3 text-xs"><p className="font-medium">Recommended member #{recommendation.recommendedMemberId} · {recommendation.score}/100</p><div className="mt-2 grid grid-cols-2 gap-1 text-[11px] text-muted-foreground">{Object.entries(recommendation.breakdown).map(([label, score]) => <span key={label}>{label}: {score}</span>)}</div><ul className="mt-2 list-inside list-disc text-[11px] text-muted-foreground">{recommendation.reason.map(reason => <li key={reason}>{reason}</li>)}</ul>{recommendation.alternatives.length > 0 && <p className="mt-2 text-[11px]">Alternatives: {recommendation.alternatives.map(item => `${item.name} (${item.score})`).join(", ")}</p>}<p className="mt-2 text-[11px] text-muted-foreground">Managers and team leads may override the recommendation by selecting another active project member before approval.</p></div>}</div>; })}
      {!tasks.some(task => !task.assigned_to) && <Empty text="No unassigned operational tasks." />}
    </Section>
    <Section title="Activity" count={activity.length}>{activity.length ? activity.slice(0, 12).map(item => <div key={item.id} className="flex gap-3 rounded-lg border border-border p-3 text-xs"><Pill tone={item.actorType === "AGENT" ? "primary" : "muted"}>{item.actorType}</Pill><div><p className="font-medium">{item.action.replaceAll("_", " ")}</p><p className="mt-1 text-[11px] text-muted-foreground">{new Date(item.createdAt).toLocaleString()} · {item.targetType} #{item.targetId}</p></div></div>) : <Empty text="Agent and human decisions will appear here." />}</Section>
  </div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg border border-border bg-card p-4"><div className="text-2xl font-semibold">{value}</div><div className="mt-1 text-[11px] text-muted-foreground">{label}</div></div>; }
function Section({ title, count, children }: { title: string; count?: number; children: React.ReactNode }) { return <section><h3 className="mb-3 text-sm font-semibold">{title}{count !== undefined && <span className="ml-2 text-xs font-normal text-muted-foreground">{count}</span>}</h3><div className="space-y-2">{children}</div></section>; }
function Empty({ text }: { text: string }) { return <div className="rounded-lg border border-dashed border-border p-5 text-center text-xs text-muted-foreground">{text}</div>; }
